### ISSUE TITLE
Adding ; as a command terminator

### ISSUE THREAD

**Issue by sohailb108** [naszly/Arduino-StaticSerialCommands#1]
If another separator like ';' is defined as a command terminator, we will be able to chain multiple commands in one line.

changes are:
in StaticSerialCommands.h:
`19+ #define CMD_TERM_3 ';'`
`62+ static const char term3 = CMD_TERM_3;`

and in StaticSerialCommands.cpp:
`74+     if (ch == term1 || ch == term2 || ch == term3) {`

now I can write commands like this:
`led on; x 100; y 100; x -100; y -100; led off`

**Comment by naszly** [comment]
Great idea!
I would love to include this in the next version; however, your changes would break string command arguments that contain ';'.
I do not wish to introduce any new termination character that can break something, or highly increase the complexity of parsing commands.
I want to introduce a way to override or extend the existing delim and termination characters, though.

**Comment by naszly** [comment]
c2a96892b96e1de21675ab91ae3f3fd96111b8af

**Comment by sohailb108** [comment]
Cool. That was a great way to implement that. I learned a lot by reading your code. Thank you.
